name: 2. Deploy to Cloudflare
run-name: Deploy to Cloudflare

on:
  workflow_dispatch:
    inputs:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_WORKER_NAME: ${{ vars.CLOUDFLARE_WORKER_NAME }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy_cloudflare_worker:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v3
      - name: Render Config
        run: |
          python render-config.py
      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          command: |
            deploy cloudflare-worker/worker.js --compatibility-date 2023-05-30 --name ${{ env.CLOUDFLARE_WORKER_NAME }}
